### ISSUE TITLE
Request: Preview Pane

### ISSUE THREAD

**Issue by four43** [madflow/flow-netbeans-markdown#14]
First off, thank you for this plugin. It is great and speeds up my writing md files workflow. I'm going to be one of "those guys" with ideas but no idea how to implement them. 

Could you move the "View Html" to a preview pane inside the IDE? Is that possible with NetBeans? The Source, History, [Preview] buttons might be a nice place.

I just found the options for the plugin. Custom CSS! Nice! For reference, this guy has some fun styles: http://jasonm23.github.io/markdown-css-themes/

Great work on the plugin. Thanks for putting the time into it.

-Seth

**Comment by madflow** [comment]
Hi,

first of all - the "View HTML" action is already embedded in the editor toolbar as an icon:

![pic](https://f.cloud.github.com/assets/183248/460450/5185202e-b41f-11e2-8412-68635cd9b57e.png)

But if I understand you correctly - you ask for a preview as an extra pane in the editor window. NetBeans supports this natively - when you select "Embedded Webkit Browser" under `Options->WebBrowser` . Instead of your external Browser - you will get the embedded one. Then you will get your extra pane for free ;)

> Another solution would be to write your own HTML Renderer and display the result in the extra pane.  But this would exceed the boundaries of this plugin.

Does this help?

Florian

**Comment by four43** [comment]
I did see that button, and that works great. Free is the best kind of extra pane! I was unaware that Netbeans could open up a web rendering pane inside the IDE. Thank you for the tip and screen shot. I will use that. 

EDIT - Actually it sounds like there is an extra plugin that is needed: Web Preview. Sounds perfect for my use case, unfortunately it is only on Windows for now. I am using a Linux environment. So not that one. There is more info detailing the issue here on SO: http://stackoverflow.com/questions/1097681/netbeans-preview-html-within-ide-split-view

**Comment by madflow** [comment]
@cr125rider Please note that we are working on a shiny new preview pane. (#36) This should come very close to what you had initially in mind.

**Comment by four43** [comment]
Thanks @madflow , I appreciate the work you guys put into this project.
