### ISSUE TITLE
Different Colors in Editor

### ISSUE THREAD

**Issue by lathspell** [madflow/flow-netbeans-markdown#16]
I use Markdown usually only in the NetBeans editor for README documents and not to generate HTML of it. For that it would be nice if the different headings would have slightly different colors. If the NetBeans editor supports underlining that could be used, too.

**Comment by madflow** [comment]
Thank you for your interest in this plugin.

I learned one has to be careful with the color settings when developing a plugin (see #3). This issue is related to your second request though - when the syntax highlighting is more reliable (see #12) then we can do fancy stuff like inline elements (bold, italic, underline etc) or different colors.

**Comment by madflow** [comment]
This feature is now in the latest master version.
