### ISSUE TITLE
Cant install on latest Netbeans 7.4

### ISSUE THREAD

**Issue by zevero** [madflow/flow-netbeans-markdown#23]
When I want to do step 2 - open the project, it doesnt get recognized as project. And instead of opening the project, just the folder opens.

It is also not possible to install the nbm file directly.

**Comment by madflow** [comment]
Hi,

"NetBeans Plugin Development" plugin must be installed if you want to compile your own binary package. Otherwise you only see a "folder". I do not know if this plugin is already available for 7.4. 

You may also install from the package provided here: https://github.com/madflow/flow-netbeans-markdown/tree/master/nbm

I have not tested this with 7.4 though,

**Comment by zevero** [comment]
Oh I see. Thank you!
The "NetBeans Plugin Development" plugin requires also JDK instead of JRE. Well I don't want to go this far and will wait until an installable is available ...
