### ISSUE TITLE
feature request : add default "github like" css for preview

### ISSUE THREAD

**Issue by djacquel** [madflow/flow-netbeans-markdown#31]
I found this to use as default css for my preview setup.
https://gist.github.com/andyferra/2554919

Thank you for the work.

David

**Comment by madflow** [comment]
Hi David,

thank you for your interest in this plugin. Could you elaborate which "Preview" you mean exactly? Since the last commit there is a (1) built-in preview right next to the "Source" and "History" Tabs in the editor and there is (2) an external preview which can be styled (Options->Miscellaneous->Markdown->HTML Export)?

Thanks!

**Comment by riker09** [comment]
I think it would make sense when the CSS applies to the build-in preview. Opening an external browser seems like one unecessary additional step.

**Comment by neilime** [comment]
+1
It will be very helpfull to custom css in "Preview" tab

**Comment by madflow** [comment]
Hi, 

thanks for the input on this. This is related to #36 - the current implementation has limited HTML/CSS support. We are gathering ideas for a non-bloat solution for this feature. 

For the time being the current "VIEW HTML" action in addtion to a configured "embedded Browser" Preview in the NetBeans default options provides a stylable preview. In the long run this should be replaced by the Preview-Pane.

**Comment by madflow** [comment]
The preview window now supports individual styling with the latest release for NetBeans 8. There is no default CSS implemented - you will have to quickly copy+paste your "github style" into the options window.
