### ISSUE TITLE
Sign plugin

### ISSUE THREAD

**Issue by taringamberini** [madflow/flow-netbeans-markdown#51]
Installing the plugin into Netbeans 7.4 it is asked if continue, or not, with the installation because the plugin is not signed: of course a decided to continue :-)

Even if this issue clearly is not a bug consider signing the plugin please.

**Comment by madflow** [comment]
Thanks for your feedback. I wonder how to sign a plugin though :D Does anyone know if this still applies:

http://wiki.netbeans.org/FaqPluginRequirements

**Comment by junichi11** [comment]
It is not necessarily to sign a nbm if we don't request verification on Plugin Portal. But we can sign it  with the following:
http://wiki.netbeans.org/DevFaqSignNbm

**Comment by jonathanlermitage** [comment]
Hi,
signing the NBM would be a great thing since it allows you to ask for validation: that means your plugin will be available in the NetBeans plugins manager.
A few things to do:
- sign your plugin and upload it to http://plugins.netbeans.org
- go to your plugin webpage and ask for validation (there is a button for each NB version you'd like to support)
- the validation team will validate your plugin asap (usually 2 or 3 days). Once it's validated, it will be available in NetBeans Tools | Plugins | Available plugins.
  The validation process is very simple: two members of the validation team will try to install, deactivate, reactivate and uninstall your plugin on a regular NetBeans IDE. If it works and if it doesn't break the IDE, your plugin is validated :)

The best way to generate a certificate and sign your plugin is effectively this how-to (for Ant based NB Module projects, it's a bit different for Maven): http://wiki.netbeans.org/DevFaqSignNbm

Do not hesitate to ask information.
Regards,

**Comment by madflow** [comment]
- Done :D Verification Pending...

I personally wanted everyone to visit the github repo first in order to facilitate contributions and general development. Let's see if we get verified ;)

**Comment by junichi11** [comment]
:+1:
