### ISSUE TITLE
Black foreground on darker LAFs

### ISSUE THREAD

**Issue by vra5107** [madflow/flow-netbeans-markdown#59]
Hi

It appears that the foreground remains black even though the UI uses darker look and feel.  I see you are using JavaFX renderer to render HTML. Most of the swing colors in Netbeans are exposed via the UIManager so that they can be reused and customized as needed. Would you be able to expose the foreground color of the preview pane for customization via UIManager ? 

This will help darker LAFs like ez-on-da-ice to play well with Markdown. FWIW, I have written and maintain ez-on-da-ice, so please let me know if there is something I can do.

Here is an example of the solution I am talking about. Please look at the OutputColors.java, specifically lines 3.217 - 3.248.

http://hg.netbeans.org/main-golden/rev/2f2b0132b1f6

And the related Bugzilla issue.
https://netbeans.org/bugzilla/show_bug.cgi?id=225439

![screenshot-2014-07-25_10 31 21](https://cloud.githubusercontent.com/assets/122128/3704128/c533228a-1410-11e4-9fff-234f972d4958.png)

**Comment by madflow** [comment]
Hi, thanks for your interest in this plugin!

Which version/branch of this plugin and JDK are you using?

In order to use JavaFX in the Netbeans 8.0 release (Marked as the "Markdown Support 2.0 for NetBeans 8.0" or the nb8 branch) you will have to explicitly enable the JavaFX preview feature under: 
- Options->Miscellaneous->Markdown->Miscellaneous

Having done this - you can style the preview pane with css under: 
- Options->Miscellaneous->Markdown->HTML Export

Does this expose  customization sufficiently - or do I not get the "real" issue? I have installed ez-on-da-ice for testing and I cannot seem spot the problem with my current setup.

**Comment by vra5107** [comment]
Hi sorry never got around to replying to you. I tested this, but I had some doubts that I wanted to clear before I messaged you, but couldn't find the time. Thankyou.
